### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by mpuff** [kristianwiklund/zigbee2soco#3]
Hello,

i get the following errors when i try to build the image:

![image](https://user-images.githubusercontent.com/13885599/140162914-29828347-5103-406f-a4c2-5fbb85d773aa.png)

i use latest raspbian buster version on a pi 4 64bit

**Comment by mpuff** [comment]
also the same on a x86 image of raspi os

**Comment by kristianwiklund** [comment]
will take a look  on this in the weekend.

**Comment by mpuff** [comment]
Thank you 🙏

**Comment by mpuff** [comment]
this was because my resolv.conf was wrong
