### ISSUE TITLE
Volume Rate Control & Long Press

### ISSUE THREAD

**Issue by mtrudel** [kristianwiklund/zigbee2soco#7]
Thanks for a great library! Works really well here, using zigbee2mqtt + mosquitto (also on S2, FWIW).

A couple of feature requests that would really finish this off:

* Provide a way to alter the volume control rate. As it is now it's dozens of turns of the symfonisk knob to go from 0 to max volume
* Support long-press to join other playing sonos devices (ie: replicate the 'hold the play button on the sonos to join the music playing in the other room' feature of the sonos devices themselves)
* Publish to docker so I can bring this into my existing mosquitto + zigbee2mqtt + homebridge compose

Thanks again for the work!

**Comment by kristianwiklund** [comment]
thanks for the feedback!

I'll take a look at it after the weekend

//Kristian

**Comment by kristianwiklund** [comment]
Rate control implemented and added as issue #9

**Comment by mtrudel** [comment]
Thanks! 
Will take a look!

**Comment by kristianwiklund** [comment]
Long press doesn't seem to be supported by the IKEA device - and my device has broken so I can't check if that is correct or not. I'll keep this open as an idea log in case I get a new controller (or manage to fix it) and long press is enabled in a newer FW but as it looks right now, it is unlikely that long press will be possible to add.
